#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPO_ROOT="$(cd "$ROOT_DIR/.." && pwd)"
COMMIT_SHA="${1:-$(git -C "$REPO_ROOT" rev-parse --short HEAD)}"
PACK_DIR="$ROOT_DIR/ops/governance_v1_3/evidence/3B-MG_PHASE1_EVIDENCE_PACK_${COMMIT_SHA}"

mkdir -p "$PACK_DIR"/{A_CI_PROOF,B_LEADS_RLS_PROOF,C_API_LEADS_HARDENING,D_DRIFT_CONTROLS,E_SUPABASE_POLICY_SNAPSHOTS}

echo "[1/8] Capturing git metadata..."
git -C "$REPO_ROOT" show -s --format=fuller "$COMMIT_SHA" > "$PACK_DIR/A_CI_PROOF/A6_commit_info.txt"

git -C "$ROOT_DIR" status --short > "$PACK_DIR/A_CI_PROOF/A5_git_status.txt"
git -C "$ROOT_DIR" diff --check > "$PACK_DIR/A_CI_PROOF/A7_git_diff_check.txt" || true

echo "[2/8] Running lint..."
(cd "$ROOT_DIR" && npm run lint) > "$PACK_DIR/A_CI_PROOF/A1_lint.txt" 2>&1

echo "[3/8] Running typecheck..."
(cd "$ROOT_DIR" && npm run typecheck) > "$PACK_DIR/A_CI_PROOF/A2_typecheck.txt" 2>&1

echo "[4/8] Running build..."
(cd "$ROOT_DIR" && npm run build) > "$PACK_DIR/A_CI_PROOF/A3_build.txt" 2>&1

echo "[5/8] Writing runtime SQL checklist..."
cat > "$PACK_DIR/A_CI_PROOF/A4_phase1_rls_tests.txt" <<'TXT'
Run docs/PHASE1_RLS_TESTS.sql in Supabase SQL editor and capture:
- Client A cannot read Client B lead
- Client B own-read with active boost
- boost_status=inactive denial
- Admin update success + client update denial
TXT

echo "[6/8] Capturing drift-control references..."
rg -n "Governance Compliance|LOCKED_SPEC_V2.1" \
  "$ROOT_DIR/.github/pull_request_template.md" \
  "$ROOT_DIR/docs/LOCKED_SPEC_V2.1.md" > "$PACK_DIR/D_DRIFT_CONTROLS/D1_D2_drift_controls.txt"

echo "[7/8] Capturing API hardening references..."
rg -n "company|rateLimit|hashIp|notifySlack|notifyEmail|lead_submitted" \
  "$ROOT_DIR/app/api/leads/route.ts" > "$PACK_DIR/C_API_LEADS_HARDENING/C0_api_leads_hardening_refs.txt"
rg -n "allowedStatuses|Forbidden|lead_updated_admin" \
  "$ROOT_DIR/app/api/admin/leads/update/route.ts" > "$PACK_DIR/C_API_LEADS_HARDENING/C0_admin_update_hardening_refs.txt"

echo "[8/8] Creating required runtime artifact placeholders..."
cat > "$PACK_DIR/B_LEADS_RLS_PROOF/B1_client_isolation_clientA_attempt.png" <<'TXT'
PLACEHOLDER: replace with screenshot proving Client A cannot read Client B lead (DENIED/EMPTY).
TXT
cat > "$PACK_DIR/B_LEADS_RLS_PROOF/B1_client_isolation_clientB_success.png" <<'TXT'
PLACEHOLDER: replace with screenshot proving Client B can read own lead when boost active.
TXT
cat > "$PACK_DIR/B_LEADS_RLS_PROOF/B2_boost_gate_inactive_denied.png" <<'TXT'
PLACEHOLDER: replace with screenshot proving boost inactive denies own-read.
TXT
cat > "$PACK_DIR/B_LEADS_RLS_PROOF/B3_admin_update_success.png" <<'TXT'
PLACEHOLDER: replace with screenshot proving admin status update succeeds.
TXT
cat > "$PACK_DIR/B_LEADS_RLS_PROOF/B3_client_update_denied.png" <<'TXT'
PLACEHOLDER: replace with screenshot proving client status update is denied by DB.
TXT

cat > "$PACK_DIR/C_API_LEADS_HARDENING/C1_rejected_submission.txt" <<'TXT'
PLACEHOLDER: paste rejected /api/leads request output (honeypot or rate-limit).
TXT
cat > "$PACK_DIR/C_API_LEADS_HARDENING/C2_notification_server_log.txt" <<'TXT'
PLACEHOLDER: paste server-side Slack/Resend notification log output (tokens redacted).
TXT
cat > "$PACK_DIR/C_API_LEADS_HARDENING/C3_boost_events_row.png" <<'TXT'
PLACEHOLDER: replace with screenshot of boost_events row for lead insert/update.
TXT

cat > "$PACK_DIR/E_SUPABASE_POLICY_SNAPSHOTS/E1_leads_rls_policies.png" <<'TXT'
PLACEHOLDER: replace with Supabase dashboard screenshot for leads RLS policies.
TXT
cat > "$PACK_DIR/E_SUPABASE_POLICY_SNAPSHOTS/E2_tables_leads_boost_events.png" <<'TXT'
PLACEHOLDER: replace with Supabase table list screenshot showing leads and boost_events.
TXT

cat > "$PACK_DIR/00_README_EVIDENCE.md" <<TXT
# 3B Media Group — Phase 1 Evidence Pack

Commit: $COMMIT_SHA
Generated by: scripts/capture_phase1_evidence.sh

This pack includes local CI logs, drift controls, and required runtime artifact filenames.
Replace placeholder files in B/C/E with actual screenshots or logs before requesting a seal.
TXT

echo "Evidence pack generated at: $PACK_DIR"
